/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 robot.gltf 
Author: Drawnah (https://sketchfab.com/EzequielMunoz)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pacobot-af0e4eb77f3c4c7da90588dc7bd92b15
Title: PacoBot
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Robot/robot.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.defaultMaterial.geometry} material={materials.Mat_Arriba} />
          <mesh geometry={nodes.defaultMaterial_1.geometry} material={materials.Mat_Cara} />
          <mesh geometry={nodes.defaultMaterial_2.geometry} material={materials.vidrio} />
          <mesh geometry={nodes.defaultMaterial_3.geometry} material={materials.Mat_Arriba} />
          <mesh geometry={nodes.defaultMaterial_4.geometry} material={materials.Mat_Brazos1} />
          <mesh geometry={nodes.defaultMaterial_5.geometry} material={materials.Mat_Rueda} />
          <mesh geometry={nodes.defaultMaterial_6.geometry} material={materials.Mat_Cuerpo} />
          <mesh geometry={nodes.defaultMaterial_7.geometry} material={materials.Mat_Cuerpo} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Robot/robot.gltf')
