/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 face.gltf 
Author: klrxyz (https://sketchfab.com/klrxyz)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/a-pink-and-black-robot-face-with-green-eyes-gol-b5bb674e2d1f44bd82f5bb3ba76fa917
Title: A pink and black robot face with green eyes, gol
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Face/face.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.ProxyMesh155994_Baked_0.geometry} material={materials.Baked} scale={0.001} />
    </group>
  )
}

useGLTF.preload('/face.gltf')
